# Generated by Django 2.0.2 on 2018-02-07 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msblog', '0002_auto_20180206_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='avatar',
            field=models.ImageField(default='pic_folder/avatar_1.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
