# Generated by Django 2.0.2 on 2018-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msblog', '0003_auto_20180207_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='avatar',
            field=models.ImageField(default='img/avatar_1.jpg', upload_to='img/'),
        ),
    ]
