# Generated by Django 2.0.2 on 2018-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msblog', '0005_auto_20180207_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='avatar',
            field=models.ImageField(default='static/img/avatar_1.jpg', upload_to='static/img/avatar/'),
        ),
    ]
